In [4]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"using {device} device")

using cpu device


In [33]:
#define the model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU() 
        )
        
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
    
model = NeuralNetwork().to(device)

print("Model Structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} \nValue: {param[:2]} \n")

Model Structure:  NeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
) 


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) 
Value: tensor([[-0.0204, -0.0210,  0.0082,  ...,  0.0049, -0.0189, -0.0153],
        [ 0.0010, -0.0307,  0.0352,  ..., -0.0253, -0.0329,  0.0133]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) 
Value: tensor([ 0.0140, -0.0051], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) 
Value: tensor([[ 0.0290,  0.0138, -0.0265,  ..., -0.0292,  0.0087,  0.0182],
        [-0.0339,  0.0119,  0.0174,  ..., -0.0302,  0.0121, -0.0088]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.bias | Size: torch.Size([512]) 
Value: tenso

In [32]:
#see weight and bais
print(f"First Linear weights: {model.linear_relu_stack[0].weight} \n")

print(f"First Linear biases: {model.linear_relu_stack[0].bias} \n")

First Linear weights: Parameter containing:
tensor([[ 0.0137,  0.0280,  0.0353,  ...,  0.0257, -0.0059, -0.0207],
        [ 0.0057,  0.0231,  0.0186,  ...,  0.0326, -0.0169, -0.0266],
        [-0.0291,  0.0108,  0.0214,  ...,  0.0159, -0.0099, -0.0263],
        ...,
        [ 0.0090,  0.0169,  0.0129,  ...,  0.0160, -0.0120, -0.0326],
        [ 0.0241,  0.0110,  0.0167,  ..., -0.0184, -0.0193, -0.0340],
        [-0.0322, -0.0245,  0.0041,  ...,  0.0293, -0.0074,  0.0064]],
       requires_grad=True) 

First Linear biases: Parameter containing:
tensor([ 0.0146, -0.0102,  0.0287,  0.0203, -0.0060, -0.0042, -0.0320,  0.0002,
        -0.0246, -0.0295,  0.0025, -0.0270, -0.0053, -0.0217, -0.0027, -0.0206,
        -0.0265,  0.0260, -0.0104, -0.0155, -0.0267, -0.0192,  0.0303,  0.0110,
         0.0152, -0.0078, -0.0008, -0.0252, -0.0343,  0.0166, -0.0351, -0.0121,
         0.0043, -0.0168, -0.0041,  0.0318,  0.0163,  0.0027, -0.0098,  0.0348,
         0.0215, -0.0217, -0.0253, -0.0014, -0.000

In [21]:
#創造image
input_image = torch.rand(3,28,28)
print(input_image.size())

#convert each 2D 28x28 image into a contiguous array of 784 pixel values
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

#applies a linear transformation on the input using its stored weights and biases
#the transformation is weight∗input+bias
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

#ReLU
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

torch.Size([3, 28, 28])
torch.Size([3, 784])
torch.Size([3, 20])
Before ReLU: tensor([[-0.5369,  0.1082,  0.0491, -0.0713, -0.2357,  0.1118,  0.4123, -0.3837,
          0.0458,  0.3784,  0.3024,  0.4699,  0.0797,  0.4634, -0.0194,  0.0229,
         -0.2723, -0.1575,  0.4920,  0.4679],
        [-0.4735,  0.1043,  0.1683,  0.0927, -0.1149,  0.1623,  0.4244, -0.3641,
         -0.1398,  0.3142,  0.2654,  0.2295,  0.1582,  0.4169, -0.0153,  0.1326,
         -0.5122, -0.3191,  0.1845,  0.4811],
        [-0.5697,  0.2815,  0.2723,  0.0789, -0.2452,  0.1002,  0.6495, -0.4420,
          0.1343,  0.0836,  0.3504, -0.0972, -0.2470,  0.1731, -0.3145, -0.1599,
          0.0207, -0.0460,  0.4405,  0.2721]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.1082, 0.0491, 0.0000, 0.0000, 0.1118, 0.4123, 0.0000, 0.0458,
         0.3784, 0.3024, 0.4699, 0.0797, 0.4634, 0.0000, 0.0229, 0.0000, 0.0000,
         0.4920, 0.4679],
        [0.0000, 0.1043, 0.1683, 0.0927, 0.0000, 0.1623, 0.4244, 0.00

In [27]:
#sequential model
seq_modules = nn.Sequential(
    nn.Flatten(),
    nn.Linear(in_features = 28*28, out_features = 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.ReLU()
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
print(logits.size())
print(logits)

softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
print(pred_probab)

torch.Size([3, 10])
tensor([[0.0000, 0.0000, 0.0000, 0.1128, 0.0000, 0.4026, 0.2332, 0.0692, 0.0000,
         0.0692],
        [0.0928, 0.0000, 0.0000, 0.0821, 0.0000, 0.4128, 0.1956, 0.0000, 0.0000,
         0.0430],
        [0.0000, 0.0000, 0.0000, 0.0984, 0.0000, 0.3336, 0.2314, 0.0422, 0.0000,
         0.0990]], grad_fn=<ReluBackward0>)
tensor([[0.0907, 0.0907, 0.0907, 0.1016, 0.0907, 0.1357, 0.1146, 0.0972, 0.0907,
         0.0972],
        [0.1002, 0.0913, 0.0913, 0.0991, 0.0913, 0.1379, 0.1110, 0.0913, 0.0913,
         0.0953],
        [0.0917, 0.0917, 0.0917, 0.1012, 0.0917, 0.1280, 0.1156, 0.0956, 0.0917,
         0.1012]], grad_fn=<SoftmaxBackward0>)
