In [2]:
import torch

In [3]:
x = torch.rand(3, 3)
print(x)

tensor([[0.4830, 0.4942, 0.1744],
        [0.4789, 0.8166, 0.4514],
        [0.6176, 0.8350, 0.0721]])


In [3]:
%matplotlib inline
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np_array value: \n {np_array} \n")
print(f"tensor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out = np_array)

print(f"Numpy np_array after *2 operation: \n {np_array} \n")
print(f"tensor x_np value after modifyding numpy array: \n {x_np} \n")


Numpy np_array value: 
 [[1 2]
 [3 4]] 

tensor x_np value: 
 tensor([[1, 2],
        [3, 4]]) 

Numpy np_array after *2 operation: 
 [[2 4]
 [6 8]] 

tensor x_np value after modifyding numpy array: 
 tensor([[2, 4],
        [6, 8]]) 



In [6]:
#繼承tensor資料型態
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype = torch.float)

print(f"Once Tensor: \n {x_ones} \n")
print(f"Random Tensor: \n {x_rand} \n")

Once Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3163, 0.2015],
        [0.2000, 0.1009]]) 



In [7]:
shape = (3, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zero Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7882, 0.0929, 0.5468],
        [0.6020, 0.4624, 0.4642],
        [0.2048, 0.6110, 0.9750]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
#attribute of a tensor
tensor1  = torch.rand(3, 4)

print(f"shape = {tensor1.shape}")
print(f"dataType = {tensor1.dtype}")
print(f"Device tensor store on: {tensor1.device}")

shape = torch.Size([3, 4])
dataType = torch.float32
Device tensor store on: cpu


In [9]:
#operation, GPU operates faster than CPU
if torch.cuda.is_available():
    tensor1 = tensor1.to('cuda')

In [10]:
tensor2 = torch.ones(4, 4)

print('first raw: ', tensor2[0])
print('first column: ', tensor2[:, 0])
print('last column: ', tensor2[:, -1])
tensor2[:, 1] = 0
print(tensor2)
print('second column: ', tensor2[:, 1])
print('second raw: ', tensor2[1, :])

#In-place operations(discourage)
tensor2.add_(3)
print(tensor2)

#jointing tensors
t1 = torch.cat([tensor2, tensor2, tensor2], dim  = 1)
print(t1)

first raw:  tensor([1., 1., 1., 1.])
first column:  tensor([1., 1., 1., 1.])
last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
second column:  tensor([0., 0., 0., 0.])
second raw:  tensor([1., 0., 1., 1.])
tensor([[4., 3., 4., 4.],
        [4., 3., 4., 4.],
        [4., 3., 4., 4.],
        [4., 3., 4., 4.]])
tensor([[4., 3., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4.],
        [4., 3., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4.],
        [4., 3., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4.],
        [4., 3., 4., 4., 4., 3., 4., 4., 4., 3., 4., 4.]])


In [11]:
#matrix multiplication
y1 = tensor2 @ tensor2.T
y2 = tensor2.matmul(tensor2.T)
y3 = torch.rand_like(tensor2)
torch.matmul(tensor2, tensor2.T, out = y3)
print(f"y1 = \n {y1} \n")
print(f"y2 = \n {y2} \n")
print(f"y3 = \n {y3} \n")

#element-wise product
z1 = tensor2 * tensor2
z2 = tensor2.mul(tensor2)
z3 = torch.rand_like(tensor2)
torch.mul(tensor2, tensor2, out = z3)
print(f"z1 = \n {z1} \n")
print(f"z2 = \n {z2} \n")
print(f"z3 = \n {z3} \n")

y1 = 
 tensor([[57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.]]) 

y2 = 
 tensor([[57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.]]) 

y3 = 
 tensor([[57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.],
        [57., 57., 57., 57.]]) 

z1 = 
 tensor([[16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.]]) 

z2 = 
 tensor([[16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.]]) 

z3 = 
 tensor([[16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.],
        [16.,  9., 16., 16.]]) 



In [12]:
agg = tensor2.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

60.0 <class 'float'>


In [13]:
#tensor to numpy array
print(f"tensor2: \n {tensor2}")
print(f"tensor2 to numPy: \n {tensor2.numpy()}")

#numPy array to tensor
n1 = np.ones(5)
np.add(n1, 1, out = n1)
print(f"numPy to tensor: \n {torch.from_numpy(n1)}")

tensor2: 
 tensor([[4., 3., 4., 4.],
        [4., 3., 4., 4.],
        [4., 3., 4., 4.],
        [4., 3., 4., 4.]])
tensor2 to numPy: 
 [[4. 3. 4. 4.]
 [4. 3. 4. 4.]
 [4. 3. 4. 4.]
 [4. 3. 4. 4.]]
numPy to tensor: 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
